// Generated by rcppr6 ({{rcppr6_version}}): do not edit by hand
#ifndef _{{PACKAGE}}_RCPPR6_PRE_HPP_
#define _{{PACKAGE}}_RCPPR6_PRE_HPP_

#include <RcppCommon.h>
namespace Rcpp {
{{rcpp_pre}}
}

#endif
