// Generated by rcppr6 ({{{rcppr6_version}}}): do not edit by hand
#ifndef _{{{PACKAGE}}}_RCPPR6_POST_HPP_
#define _{{{PACKAGE}}}_RCPPR6_POST_HPP_

#include <Rcpp.h>
#include <{{{package}}}/rcppr6_support.hpp>
namespace Rcpp {
{{{rcpp_post}}}
}

#endif
